### PR TITLE
Remove a repeat fortune from pets, remove poorly formatted goldfish fortune, remove reference to suicide in pets

### PR DESCRIPTION
**Pull request by OulipianSummer**
This is my first contribution to open source!

This commit contains the addition of the pets file to the new fortunes base.

In the spirit of making this application a more hand-picked experience, I removed two fortunes that featured references to animal violence, and one fortune that contained a reference to suicide. I also removed  a repeated fortune ("all intelligent species own cats").

If needed, I could move the questionable-content fortunes to "off".

### CODE REVIEW

**Review by cafkafk — CHANGES_REQUESTED** [review]
> This is my first contribution to open source!

Hi, hope you have a good time! :tada: 

> This commit contains the addition of the pets file to the new fortunes base.
> In the spirit of making this application a more hand-picked experience, I removed two fortunes that featured references to animal violence, and one fortune that contained a reference to suicide. I also removed a repeated fortune ("all intelligent species own cats").

Thanks, I think this sounds good. However, one things I'd like is if you could also remove the things you've moved here from `oldtunes/pets` + the fortunes that you think were offensive.

> If needed, I could move the questionable-content fortunes to "off".

Are you referring to the ones removed here?

**Comment by cafkafk** [comment]
Ohh, and if you removed all of them, you can just delete the file!

**Comment by cafkafk** [comment]
> Yes: the the fortunes I removed based on content could conceivably be moved to `off`, but I think that would require them having at least some editorial value outside of the offensive punchline, and I'm not sure they do.

Agreed, let's just have them gone for good.

> Maybe having an editorial guide for this project would make auditing the fortunes a bit easier, but in the mean time I've just been looking for fortunes that pass my own smell test which could be wrong.

I agree, if you're willing, you could make a PR for that, perhaps in the root of the project as `EDITORIAL.md` or something like that?

**Review by cafkafk — APPROVED** [review]

**Comment by OulipianSummer** [comment]
> I agree, if you're willing, you could make a PR for that, perhaps in the root of the project as `EDITORIAL.md` or something like that?

Sure thing! I can draft up a PR for review.

**Comment by cafkafk** [comment]
> > I agree, if you're willing, you could make a PR for that, perhaps in the root of the project as `EDITORIAL.md` or something like that?
> 
> Sure thing! I can draft up a PR for review.

That would be cool!

**Pull request merged**
